Django 2.1 update was causing for a new Error
The error was: render() got an unexpected keyword argument 'renderer'
This is from an update in Django. The solution was proposed here: 
https://stackoverflow.com/questions/52039654/django-typeerror-render-got-an-unexpected-keyword-argument-renderer